### ISSUE TITLE
Base64 convertor lack of try/catch block

### ISSUE THREAD

**Issue by comargo** [TheJelle/OpenDeCoder#1]
at https://github.com/TheJelle/OpenDeCoder/blob/master/STDCoder/Conversion/Base64.cs#L116 I've got a exception when tried to bruteforce the password.
pattern is AQ=M (with another code the pattern was longer, but the equal sign was not at last place)

**Comment by JulienKluge** [comment]
Thanks for submitting this issue and confirmed. ^^
I'll fix it in the next few hours/days.

**Comment by JulienKluge** [comment]
done
